---
version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: .dockerdev/dev.Dockerfile
    command: go run .
    volumes:
      - .:/app
      - go-modules:/go/pkg/mod
    ports:
      - '9321:8080'
    stdin_open: true
    tty: true

volumes:
  go-modules:
