---
version: '3.7'

services:
  # redis:
  #   image: redis:${REDIS_VERSION:-7-alpine}
  #   ports:
  #     - '16329:6379'
  #   volumes:
  #     - redis_data:/data
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "ping"]
  #     interval: 1s
  #     timeout: 3s
  #     retries: 10

  app:
    build:
      context: .
      dockerfile: .dockerdev/dev.Dockerfile
    command: go run .
    volumes:
      - .:/app
      - go-modules:/go/pkg/mod
    ports:
      - '9321:8080'
    stdin_open: true
    tty: true
    # depends_on:
    #   redis:
    #     condition: service_healthy

volumes:
  # redis_data:
  go-modules:
